version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "slot-machine"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gx2gy3vtogos"
s3_prefix = "slot-machine"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
